### PR TITLE
Update Scalding to 0.12.0 and CDH 5.3.0

### PR DESCRIPTION
**Pull request by mattweyant**
This may address https://github.com/ParallelAI/SpyGlass/issues/20.

### CODE REVIEW

**Comment by galarragas** [comment]
Thanks @mattweyant

**Comment by mattweyant** [comment]
No problem!

**Comment by xgdgsc** [comment]
So I should use the master if I use CDH 5.3.0? Can you make a release at http://conjars.org/repo/parallelai/parallelai.spyglass/ to make installation easier?

**Comment by xgdgsc** [comment]
When I try `$ mvn clean install -U` error occurs: 
[ERROR] Failed to execute goal on project parallelai.spyglass: Could not resolve dependencies for project parallelai:parallelai.spyglass:jar:2.10_0.12.0_5.3.0: Could not find artifact org.apache.hbase:hbase:jar:0.98.6-cdh5.3.0 in scala-tools.org (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]

**Comment by mattweyant** [comment]
Not sure why it's attempting to pull CDH dependencies from Sonatype. They are available from Cloudera directly, and the Cloudera repo is included in the POM.

**Comment by Antwnis** [comment]
The reason that it's not picking up the JAR is that it no longer exists !!

HBase has now being split in hbase-client / hbase-server etc etc

I attempted a quick fix here https://github.com/ParallelAI/SpyGlass/commit/dcd247b9b00bd70f7749b1d1ca8d69552a44fae4 and deployed a new version on Conjars. Try

<dependency>
  <groupId>parallelai</groupId>
  <artifactId>parallelai.spyglass</artifactId>
  <version>2.10_0.12.0_5.3.0_beta</version>
</dependency>

The possibility of this working is not huge, so please test and provide feedback - to make a proper release if things are up and working

**Comment by mattweyant** [comment]
Ah, yes! Thanks, @Antwnis. I was hasty in pushing the change. We found the same issue later in the day yesterday during testing.

**Comment by mattweyant** [comment]
@Antwnis I tested `2.10_0.12.0_5.3.0_beta` locally and it appears to work just fine.

**Comment by mattweyant** [comment]
Another particularly unsettling problem is now with CDH5.3.0 itself: http://community.cloudera.com/t5/Batch-Processing-and-Workflow/CDH-5-3-CLASSPATH-Issue/td-p/23188

**Comment by xgdgsc** [comment]
@Antwnis Your fix is fine but the deployed pom: http://conjars.org/repo/parallelai/parallelai.spyglass/2.10_0.12.0_5.3.0_beta/parallelai.spyglass-2.10_0.12.0_5.3.0_beta.pom is still the old version and gives the same error. I had to comment it out manually.

**Pull request merged**
